# template environment configuration
# copy this file to generate more configurations, for example for `dev`, `staging`, and
# `prod` environments

# general settings
namespace: to-set
postfix: 0001
environment: to-set

# model settings
# based on the provided `model_group_name`, the `get_latest_approved_model.py` script
# extends the yaml file with the variable `model_arn` that are needed for terraform
# to run successfully
model_group_name: to-set
model_arn: <get-from-script>
execution_role_arn: to-set

# endpoint configuration settings
instance_type: to-set
instance_count: 1

# data capture settings
enable_data_capture: true
create_s3_bucket: true
s3_bucket_name: to-set
s3_bucket_force_destroy: false
sampling_percentage: 100
data_capture_s3_upload_path: "s3://$(s3_bucket_name)/"

# autoscaling settings
enable_autoscaling: false
min_capacity: -1
max_capacity: -1

# target tracking scaling policy
# autoscaling_type: "target_tracking"
policy_target_value: -1
scale_in_cooldown: -1
scale_out_cooldown: -1

# step scaling policy
autoscaling_type: "step_scaling"

step_scaling_scale_out_threshold: -1
step_scaling_scale_out_period: -1
step_scaling_scale_out_evaluation_periods: -1

step_scaling_scale_in_threshold: -1
step_scaling_scale_in_period: -1
step_scaling_scale_in_evaluation_periods: -1
