# dev environment configuration

# general settings
namespace: musicgen-project
postfix: '0001'
environment: dev

# model settings
# based on the provided `model_group_name`, the `get_latest_approved_model.py` script
# extends the yaml file with the variable `model_arn` that are needed for terraform
# to run successfully
model_group_name: musicgen-model
model_arn: <get_from_script>
execution_role_arn: arn:aws:iam::138140302683:role/service-role/AmazonSageMaker-ExecutionRole-20230522T162566

# endpoint configuration settings
instance_type: ml.g4dn.xlarge
instance_count: 1

# data capture settings
enable_data_capture: false
create_s3_bucket: false
s3_bucket_name: -1
s3_bucket_force_destroy: true
sampling_percentage: 100
data_capture_s3_upload_path: s3://$(s3_bucket_name)/

# autoscaling settings
enable_autoscaling: false
min_capacity: -1
max_capacity: -1

# target tracking scaling policy
autoscaling_type: "target_tracking"
policy_target_value: -1
scale_in_cooldown: -1
scale_out_cooldown: -1

# step scaling policy
step_scaling_scale_out_threshold: -1
step_scaling_scale_out_period: -1
step_scaling_scale_out_evaluation_periods: -1

step_scaling_scale_in_threshold: -1
step_scaling_scale_in_period: -1
step_scaling_scale_in_evaluation_periods: -1