name: endpoint-plan

on:
  workflow_dispatch:
  # push:

jobs:
  endpoint-plan:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/helpers-terraform-execute-template.yaml
    with:
      tf_action: plan
      aws_role: <YOUR-ROLE-HERE>
      aws_role_region: us-east-1
      root_folder: aws/terraform/provision_endpoint/src
